---
title: Santiago Ruffino's Blog
description: Is not another programming blog
language: en
domain: https://santiruffino.com
incremental: false # Change to `true` if your server support keeping `.cache` and `public` folders
repository: https://github.com/santiruffino/personal-blog
analytics: UA-140142531-1
social:
  twitter: santiruffinodev
  github: santiruffino
icon: /static/icon_48.png